//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/NewInputSystem/TileControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TileControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TileControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TileControl"",
    ""maps"": [
        {
            ""name"": ""Tile"",
            ""id"": ""f882f468-63ad-4fcc-9445-614eb26d06c6"",
            ""actions"": [
                {
                    ""name"": ""Press"",
                    ""type"": ""Button"",
                    ""id"": ""85cc383c-f59d-4bbe-8887-93781f81ef82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""feaaac74-68d6-4f53-8d4b-8dd8f2fcb483"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Tile
        m_Tile = asset.FindActionMap("Tile", throwIfNotFound: true);
        m_Tile_Press = m_Tile.FindAction("Press", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Tile
    private readonly InputActionMap m_Tile;
    private List<ITileActions> m_TileActionsCallbackInterfaces = new List<ITileActions>();
    private readonly InputAction m_Tile_Press;
    public struct TileActions
    {
        private @TileControl m_Wrapper;
        public TileActions(@TileControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @Press => m_Wrapper.m_Tile_Press;
        public InputActionMap Get() { return m_Wrapper.m_Tile; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TileActions set) { return set.Get(); }
        public void AddCallbacks(ITileActions instance)
        {
            if (instance == null || m_Wrapper.m_TileActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TileActionsCallbackInterfaces.Add(instance);
            @Press.started += instance.OnPress;
            @Press.performed += instance.OnPress;
            @Press.canceled += instance.OnPress;
        }

        private void UnregisterCallbacks(ITileActions instance)
        {
            @Press.started -= instance.OnPress;
            @Press.performed -= instance.OnPress;
            @Press.canceled -= instance.OnPress;
        }

        public void RemoveCallbacks(ITileActions instance)
        {
            if (m_Wrapper.m_TileActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITileActions instance)
        {
            foreach (var item in m_Wrapper.m_TileActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TileActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TileActions @Tile => new TileActions(this);
    public interface ITileActions
    {
        void OnPress(InputAction.CallbackContext context);
    }
}
